In [6]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [10]:
lst = [i for i in range(1, 11)]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
for i in range(len(lst)):
    lst[i] *= 5

print(lst)

[25, 50, 75, 100, 125, 150, 175, 200, 225, 250]


In [40]:
arr = np.array([i for i in range(1, 11)])
arr
arr = arr*5
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [42]:
arr = np.arrange(1, 11, 11)
arr

AttributeError: module 'numpy' has no attribute 'arrange'

In [44]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
arr = np.arange(1, 11, 3)
arr

array([ 1,  4,  7, 10])